site_name: Exceed TurboX
site_author: Rocket Software
docs_dir: docs

theme:
  name: material
  custom_dir: /overrides
  language: en
  logo: images/RocketSoftware_Stack-RGB-White.png
  favicon: images/favicon-rocket.ico
  features:
    - navigation.instant
    - navigation.indexes

extra:
    version: V12.5.4
    bundle: etx-authsvr-1254

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - meta
  - def_list

plugins:
  - offline
  - search:
      lang:
        - en
  - literate-nav:
      nav_file: nav.md
  - mkdocs-simple-hooks:
      hooks:
        on_config: "pdf_config:configure_pdf"
  - with-pdf:
      cover_subtitle: 'Authentication Server'
      ordered_chapter_level: 1
      toc_title: Table of Contents
      output_path: 'pdf/etx-auth-server-guide-1254.pdf'
  - macros:
      include_yaml:
        - data/variables-etx.yml
